Teach extras/build to cross-compile and statically link.

diff --git a/extras/build b/extras/build
--- a/extras/build
+++ b/extras/build
@@ -14,95 +14,158 @@
 # License: GPLv2
 #
 Progs="fitzp"
+
+# Relative path to protobuf sources
+# e.g. src/foo/a.proto
 Protobufs="src/lib/securl/enc.proto"
-pwd=`pwd`
+
+
+# -- DO NOT CHANGE ANYTHING AFTER THIS --
+
 Z=`basename $0`
+PWD=`pwd`
+
+Static=0
+Dryrun=0
+Prodver=0.1
+
+hostos=$(go env GOHOSTOS)       || exit 1
+hostcpu=$(go env GOHOSTARCH)    || exit 1
+
 
 die() {
     echo "$Z: $@" 1>&2
-    exit 1
+    exit 0
+}
+
+case $BASH_VERSION in
+    4.*.*) ;;
+
+    *) die "I need bash 4.x to run!"
+        ;;
+esac
+
+warn() {
+    echo "$Z: $@" 1>&2
 }
 
 usage() {
+
     cat <<EOF
+$0 - A Go production build tool that adds git-repository information,
+product version, build-timestamp etc. It supports cross-compilation,
+static linking and generating protobuf output.
+
+It uses the gogo-slick protobuf compiler [github.com/gogo/protobuf].
+
+Build output is in bin/\$OS-\$CPU for a given OS, CPU combination.
+
 Usage: $0
-       $0 [options] OS-ARCH [PROGS]
-       $0 -- [PROGS]
+       $0 [options] [PROGS]
 
 Where OS-ARCH denotes one of the valid OS, ARCH combinations supported by 'gg'.
-And, PROGS is one or more of $Progs
+And, PROGS is one or more go programs.
 
 With no arguments, $0 builds: $Progs
 
 Options:
-    -h, --help          show this help message and quit
-    -s, --static        build a static binary [dynamic]
-    -v N, --version=N   use 'N' as the product version string [0.1]
-    -a X, --arch=X      cross build for architecture 'X'
-    -x                  run in debug/trace mode
+    -h, --help          Show this help message and quit
+    -, --static         Build a statically linked binary [False]
+    -V N, --version=N   Use 'N' as the product version string [$Prodver]
+    -a X, --arch=X      Cross compile for OS-CPU 'X' [$hostos-$hostcpu]
+    -n, --dry-run       Dry-run, don't actually build anything [False]
+    -x                  Run in debug/trace mode [False]
 EOF
 
-    return 0
+    exit 0
 }
 
+host=`uname|tr '[A-Z]' '[a-z]'`
+export GO15VENDOREXPERIMENT=1
 
-static=
-pver="0.1"  # default product version
-trace=
-arch=
+declare -A oses
+declare -A cpus
+declare -A cgo
+
+# Supported & Verified OS/CPU combos for this script
+oslist="linux android openbsd freebsd darwin dragonfly netbsd windows"
+needcgo="android"
+cpulist="i386 amd64 arm arm64"
+cpualias_i386="i486 i586 i686"
+cpualias_amd64="x86_64"
+cpualias_arm64="aarch64"
+
+# CGO Cross-Compilers for various CPU+OS combinations of Android
+android_i386=i686-linux-android-gcc
+android_arm64=aarch64-linux-android-gcc
+android_arm=arm-linux-androideabi-gcc
+
+# initialize the various hash tables
+for o in $oslist;  do oses[$o]=$o; done
+for o in $needcgo; do cgo[$o]=$o;  done
+for c in $cpulist; do
+    cpus[$c]=$c
+    a="cpualias_$c"
+    a=${!a}
+    for x in $a; do cpus[$x]=$c; done
+done
+
+
+doinit=0
 args=
-arg=
-prev=
-for arg
+
+#set -x
+ac_prev=
+for ac_option
 do
   shift
 
-  if [ -n "$prev" ]; then
-    eval "$prev=\$arg"
-    prev=
+  if [ -n "$ac_prev" ]; then
+    eval "$ac_prev=\$ac_option"
+    ac_prev=
     continue
   fi
 
-  case "$arg" in
-      -*=*) optarg=`echo "$arg" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
-      *) optarg= ;;
+  case "$ac_option" in
+      -*=*) ac_optarg=`echo "$ac_option" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
+      *) ac_optarg= ;;
   esac
 
 
-  case "$arg" in
+  case "$ac_option" in
         --help|-h|--hel|--he|--h)
             usage;
-            exit 0
             ;;
 
         --arch=*)
-            arch=$optarg
+            Arch=$ac_optarg
             ;;
-
         -a|--arch)
-            prev=arch
+            ac_prev=Arch
             ;;
 
         --version=*)
-            pver=$optarg
+            Prodver=$ac_optarg
+            ;;
+        -V|--version)
+            ac_prev=Prodver
             ;;
 
-        -v|--version)
-            prev=pver
+        -s|--static)
+            Static=1
+            ;;
+
+        --dry-run|-n)
+            Dryrun=1
             ;;
 
         --debug|-x)
-            trace="-x"
             set -x
-            ;;
-
-        --static|-s)
-            static=1
             ;;
 
         *) # first non option terminates option processing.
            # we gather all remaining args and bundle them up.
-            args="$args $arg"
+            args="$args $ac_option"
             for xx
             do
                 args="$args $xx"
@@ -111,6 +174,61 @@ do
             ;;
   esac
 done
+[ $Dryrun  -gt 0 ] && e=echo
+
+# This fragment can't be in a function - since it exports several vars
+if [ -n "$Arch" ]; then
+    ox=${Arch%%-*}
+    cx=${Arch##*-}
+    [ "$ox" = "$cx" ] && cx=$hostcpu
+
+    os=${oses[$ox]}
+    cpu=${cpus[$cx]}
+    [ -z "$os" ]  && die "Don't know anything about OS $ox"
+    [ -z "$cpu" ] && die "Don't know anything about CPU $cx"
+
+    export GOOS=$os GOARCH=$cpu
+    cross=$os-$cpu
+
+else
+    os=$hostos
+    cpu=$hostcpu
+    cross=$os-$cpu
+fi
+
+# If we don't need CGO, then we can attempt a static link
+if [ -n "${cgo[$os]}" ]; then
+    export CGO_ENABLED=1
+
+    # See if we have a specific cross-compiler for this CPU+OS combo
+    xcc="${GOOS}_${GOARCH}"
+    xcc=${!xcc}
+    if [ -n "$xcc" ]; then
+        p=`type -p $xcc`
+        [ -n "$p" ] || die "Can't find $xcc! Do you have compilers for $GOARCH available in PATH?"
+        export CC=$xcc
+    else
+        echo "$Z: No Cross compiler defined for $GOOS-$GOARCH. Build may fail.." 1>&2
+    fi
+else
+    if [ $Static -gt 0 ]; then
+        export CGO_ENABLED=0
+
+        isuffix="--installsuffix cgo"
+        ldflags="-s"
+        msg="statically linked"
+    fi
+fi
+
+# Sane GOPATH
+export GOPATH=$PWD/vendor:$PWD
+
+# This is where build outputs go
+Bindir=$PWD/bin/$cross
+Hostbindir=$PWD/bin/$hostos-$hostcpu
+
+[ -d $Bindir ]     || mkdir -p $Bindir
+[ -d $Hostbindir ] || mkdir -p $Hostbindir
 
 
 # Get git/hg version info for the build
@@ -122,9 +240,8 @@ if [ -d "./.hg" ]; then
     else
         rev="hg:${brev}"
     fi
-        
 elif [ -d "./.git" ]; then
-    xrev=$(git describe --always --dirty --long --abbrev=12) || exit 1
+    xrev=$(git describe --always --dirty --long --abbrev=12)
     rev="git:$xrev"
 else
     rev="UNKNOWN-VER"
@@ -133,11 +250,17 @@ fi
 
 # Do Protobufs if needed
 if [ -n "$Protobufs" ]; then
+    slick=$Hostbindir/protoc-gen-gogoslick
     pc=$(type -p protoc)
-    slk=$(type -p protoc-gen-gogoslick)
 
     [ -z "$pc" ] && die "Need 'protoc' for building .."
-    [ -z "$slk" ] && die "Need 'protoc-gen-gogoslick' for building .."
+
+    if [ ! -f $slick ]; then
+        echo "Building $slick .."
+        $e go build -o $slick github.com/gogo/protobuf/protoc-gen-gogoslick || exit 1
+    fi
+
+    export PATH=$PATH:$Hostbindir
 
     for f in $Protobufs; do
         dn=$(dirname $f)
@@ -145,44 +268,28 @@ if [ -n "$Protobufs" ]; then
         of=$dn/${bn}.pb.go
         if [ $f -nt $of ]; then
             echo "Running $pc .."
-            $pc --gogoslick_out=. $f || exit 1
+            $e $pc --gogoslick_out=. $f || exit 1
         fi
     done
 fi
 
+repover="main.RepoVersion=$rev"
+prodver="main.ProductVersion=$Prodver"
+date="main.Buildtime=`date -u '+%Y-%m-%dT%H:%M.%SZ'`"
+ldflags="-ldflags \"-X $repover -X $prodver -X $date $ldflags\""
+
+
 set -- $args
-
-# figure out what our env is and setup appropriate bin dir
-[ -n "$arch" ]   && cross="--arch=$arch"
-
-if [ -n "$static" ]; then
-    export CGO_ENABLED=0
-    isuffix="--installsuffix cgo"
-    ldflags="-s"
-    staticmsg="statically linked"
-fi
-
-GOOS=$(./gg $cross env GOOS)      || exit 1
-GOARCH=$(./gg $cross env GOARCH)  || exit 1
-bindir=$pwd/bin/${GOOS}-${GOARCH}
-mkdir -p $bindir                  || exit 1
-
 if [ -z "$1" ]; then
     all=$Progs
 else
     all="$@"
 fi
 
-echo "Building $rev .. $arch $staticmsg"
+echo "Building $rev, $cross $msg .."
 
-# Put build time stamp and repo version
-ver="main.RepoVersion=$rev"
-prodver="main.ProductVersion=$pver"
-date="main.Buildtime=`date -u '+%Y-%m-%dT%H:%M.%SZ'`"
-ldflags="-ldflags=\"-X $ver -X $prodver -X $date $ldflags\""
-
-for p in $all; do
-    echo "$p .."
-    ./gg $trace $cross build -o $bindir/$p $isuffix "$ldflags" $p || exit 1
+for p in $all; do 
+    echo "   $p .."
+    $e eval go build -o $Bindir/$p $isuffix "$ldflags" $p || exit 1
 done
-# .. vim: ft=sh:expandtab:ts=4:sw=4:tw=96:
+# .. vim: ft=sh:expandtab:ts=4:sw=4:tw=84:
